# Generated by Django 5.2.5 on 2025-11-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('stego_media', models.FileField(blank=True, null=True, upload_to='stego_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.FileField(blank=True, null=True, upload_to='results/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
