# Generated by Django 5.2.5 on 2025-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograapp', '0002_upload_alter_user_confirmpassword_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('files_processed_number', models.IntegerField(blank=True, null=True)),
                ('encode_number', models.IntegerField(blank=True, null=True)),
                ('decode_number', models.IntegerField(blank=True, null=True)),
                ('encode_text_in_image_number', models.IntegerField(blank=True, null=True)),
                ('decode_text_in_image_number', models.IntegerField(blank=True, null=True)),
                ('encode_image_in_image_number', models.IntegerField(blank=True, null=True)),
                ('decode_image_in_image_number', models.IntegerField(blank=True, null=True)),
                ('encode_video_in_image_number', models.IntegerField(blank=True, null=True)),
                ('decode_video_in_image_number', models.IntegerField(blank=True, null=True)),
                ('encode_audio_in_image_number', models.IntegerField(blank=True, null=True)),
                ('decode_audio_in_image_number', models.IntegerField(blank=True, null=True)),
                ('encode_text_in_video_number', models.IntegerField(blank=True, null=True)),
                ('decode_text_in_video_number', models.IntegerField(blank=True, null=True)),
                ('encode_image_in_video_number', models.IntegerField(blank=True, null=True)),
                ('decode_image_in_video_number', models.IntegerField(blank=True, null=True)),
                ('encode_text_in_audio_number', models.IntegerField(blank=True, null=True)),
                ('decode_text_in_audio_number', models.IntegerField(blank=True, null=True)),
                ('encode_image_in_audio_number', models.IntegerField(blank=True, null=True)),
                ('decode_image_in_audio_number', models.IntegerField(blank=True, null=True)),
                ('date_encode_text_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_text_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_image_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_image_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_video_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_video_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_audio_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_audio_in_image_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_text_in_video_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_text_in_video_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_image_in_video_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_image_in_video_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_text_in_audio_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_text_in_audio_number', models.DateTimeField(auto_now_add=True)),
                ('date_encode_image_in_audio_number', models.DateTimeField(auto_now_add=True)),
                ('date_decode_image_in_audio_number', models.DateTimeField(auto_now_add=True)),
                ('last_encryption_type', models.DateTimeField(auto_now=True)),
                ('second_last_encryption_type', models.DateTimeField(auto_now=True)),
                ('third_last_encryption_type', models.DateTimeField(auto_now=True)),
                ('last_decryption_type', models.DateTimeField(auto_now=True)),
                ('second_last_decryption_type', models.DateTimeField(auto_now=True)),
                ('third_last_decryption_type', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
