# Generated by Django 5.2.5 on 2026-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograapp', '0004_detail_decode_audio_in_audio_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
